### ISSUE TITLE
0.4.0 checklist / upcoming breaking changes

### ISSUE THREAD

**Issue by bluss** [bluss/rust-itertools#46]
ticks are for my WIP

- [x] Remove deprecated items (icompr, fn_map, etc.)
- [x]  Mark Slice trait unsafe
- ~~Rename MergeAscend to MergeFn (?)~~
- [ ] Generalize .format to debug / display(?)
- [x] Merge / MergeBy without fn() #49
- [x] Dedup without fn() #49 
- [x] Unique without fn() #49
- [x] MendSlices without fn() #49
- [x] Rename sort_by → sorted_by
- [x] Remove times()
- [x] interleave_shortest not fused
